Repository sergi-svg/homework-java-ironbattle, pull requests merged in 2024-02, with the labels that each got.

#1 Added .gitignore
  .gitignore
Labels: enhancement

#2 Feature diagram
  README.md
  iron-battle.drawio
Labels: enhancement

#10 Add final to MIN_HP_WIZARD and MAX_HP_WIZARD constants
  src/Wizard.java
Labels: enhancement

#12 Warrior class v1
  src/Character.java
  src/Warrior.java
  src/src.iml
Labels: enhancement

#13 Add mana and intelligence attributes to the Wizard
  src/Wizard.java
Labels: enhancement

#11 add utils class and generateRandomInt method
  src/Utils.java
Labels: enhancement

#16 update generateRandomInt method in Utils
  src/Utils.java
Labels: enhancement

#15 Updated Warrior class with creation
  src/Warrior.java
Labels: enhancement

#18 Attack wizard
  src/Wizard.java
Labels: enhancement

#20 Implementing attack method for the Wizard character
  src/Wizard.java
Labels: enhancement

#21 Implementing attack method for the Wizard character
  src/Wizard.java
Labels: enhancement

#27 fullRandomBattle completed
  src/BattleSimulator.java
  src/Character.java
  src/Characters.java
  src/Colors.java
  src/Stats.java
  src/Utils.java
  src/Warrior.java
  src/Wizard.java
  src/characters.csv
  src/src.iml
Labels: enhancement

#28 Sergi svg patch 1
  .DS_Store
  .gitignore
  iron-battle.drawio
Labels: invalid

#30 work on customizeCharactersNameAndTypeBattle
  src/BattleSimulator.java
Labels: enhancement

#31 Implementing attack method for the Wizard character
  src/model/Wizard.java
Labels: bug

#32 Customize characters features
  src/BattleSimulator.java
  src/model/Warrior.java
  src/model/Wizard.java
Labels: enhancement

#33 Renaming enum values for java convention
  src/BattleSimulator.java
  src/model/Warrior.java
  src/model/Wizard.java
  src/utils/Characters.java
  src/utils/Colors.java
  src/utils/Stats.java
Labels: bug

#36 Show winner
  src/model/Battle.java
Labels: enhancement

#37 show tittle
  src/BattleSimulator.java
  src/model/Battle.java
  src/utils/Utils.java
Labels: enhancement

#38 Implementing attack method for the Wizard character
  src/BattleSimulator.java
  src/model/Warrior.java
  src/model/Wizard.java
  src/utils/Utils.java
Labels: enhancement

#39 Develop
  src/BattleSimulator.java
  src/model/Battle.java
  src/model/Warrior.java
  src/model/Wizard.java
  src/utils/BattleType.java
  src/utils/CharacterType.java
  src/utils/Characters.java
  src/utils/Color.java
  src/utils/Utils.java
Labels: enhancement
